server:
  port: 8090
info:
  app:
    version: '0.0.1-SNAPSHOT'
    description: 'Employee Service'
    hostname: http://localhost:8090

spring:
  jpa:
    show_sql: true
    format_sql: true
    properties:
      hibernate:
        default_schema: ass
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: database/changelog/changelog-master.xml
    enabled: true
    liquibaseSchema: liquibase
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver: org.postgresql.Driver
    username: postgres
    password: admin
    hikari:
      minimumIdle: 1
      maximumIdle: 2
      maximumPoolSize: 25
      idleTimeout: 15000
      connectionTimeout: 300000
      leakDetectionThreshold: 60000
      maxLifetime: 600000

springdoc:
  swagger-ui:
    operationsSorter: method
  api-docs:
    path: /api-docs